#!/bin/bash
set -e

# start by removing unwanted packages

if ! [ -f stamp-removal ]; then 
    apt-get -y remove lxde lxde-core || true
    apt-get -y remove plymouth leafpad || true
    sudo apt-get autoremove
    touch stamp-removal
fi

if ! [ -f stamp-update ]; then 
    apt-get update && touch stamp-update
fi

if ! [ -f stamp-upgrade ]; then
    apt-get -y upgrade && touch stamp-upgrade
fi


if ! [ -f stamp-mytools ]; then
    mytools="emacs23 rsync devscripts xxdiff-scripts screen rdiff-backup most"
    apt-get -y install $mytools && touch stamp-mytools
fi



if ! [ -f stamp-servers ]; then
    servers="apache2 postgresql gkrellmd"
    apt-get -y install $servers && touch stamp-servers
fi


if ! [ -f stamp-admin ]; then
    admin="etckeeper"
    apt-get -y install $admin && touch stamp-admin
fi



