#!/bin/bash
set -e

# start by removing unwanted packages
if ! [ -f stamp-removal ]; then 
    apt-get -y remove lxde lxde-core || true
    apt-get -y remove plymouth leafpad || true
    sudo apt-get autoremove
    touch stamp-removal
fi

# update the package lists
if ! [ -f stamp-update ]; then 
    apt-get update && touch stamp-update
fi

# upgrade the system
if ! [ -f stamp-upgrade ]; then
    apt-get -y upgrade && touch stamp-upgrade
fi

# install admin tools first (use etckeeper to keep track of config)
if ! [ -f stamp-admin ]; then
    admin="etckeeper iotop reprepro"
    apt-get -y install $admin && touch stamp-admin
fi

# install my handy dandy tools
if ! [ -f stamp-mytools ]; then
    mytools="emacs23 rsync devscripts xxdiff-scripts screen rdiff-backup most"
    mytools="$mytools keychain"
    apt-get -y install $mytools && touch stamp-mytools
fi

# install services
if ! [ -f stamp-servers ]; then
    servers="apache2 libapache2-mod-wsgi postgresql gkrellmd"
    apt-get -y install $servers && touch stamp-servers
fi

# install necessary python packages
if ! [ -f stamp-python ]; then
    python="python-dev virtualenvwrapper"
    apt-get -y install $python && touch stamp-python
fi

# this builds psycopg in the virtualenv
if ! [ -f stamp-libdevel ]; then
    libdevel="libpq-dev"
    apt-get -y install $libdevel && touch stamp-libdevel
fi




